patchesStrategicMerge:
- database-connection-sealed-secret.yaml
- rabbitmq-connection-sealed-secret.yaml
- database-migration-connection-sealed-secret.yaml
images:
- name: greenstand/webmap-query-service-consumer
  newTag: 1.10.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
