DROP INDEX IF EXISTS rcapturef_status_idx;
DROP INDEX IF EXISTS rcapturef_fieldusr_idx;
DROP INDEX IF EXISTS rcapturef_fieldusrname_idx;
DROP INDEX IF EXISTS rcapturef_crdate_idx;
DROP INDEX IF EXISTS rcapturef_trckgsess_idx;
DROP INDEX IF EXISTS rcapturef_attrbs_idx;
DROP INDEX IF EXISTS rcapturef_map_name_idx;
DROP INDEX IF EXISTS rcapturef_sessn_idx;
DROP TABLE IF EXISTS raw_capture_feature;