# Only needed if microservice contains db migrations
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-wait-for
subjects:
  - kind: ServiceAccount
    name: default
    namespace: #treetracker-microservice-name#
roleRef:
  kind: ClusterRole
  name: k8s-wait-for
  apiGroup: rbac.authorization.k8s.io 