# Only needed if microservice contains db migrations
apiVersion: batch/v1
# Only needed if microservice contains db migrations
kind: Job
metadata:
  name: #microservice name migration job#
spec:
  backoffLimit: 1 # allow for one re-try of the migration
  template:
    spec:
      containers:
      - name: migration
        image: greenstand/#treetracker-microservice-name#:VERSION
        env:
          - name: BASE_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: treetracker-api-database-connection
                key: db
          - name: DATABASE_URL
            value: "$(BASE_DATABASE_URL)&schema=<microservice schema name>"
        command: ["node"]
        args: ["node_modules/db-migrate/bin/db-migrate", "up", "--migrations-dir", "database/migrations/", "-v"]
      restartPolicy: Never