apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-connection
  namespace: webmap
spec:
  encryptedData:
    messageQueue: AgCTmt39TXdDGT7TFV1cupfvF2WVAWDPxlqkCB5nlseYsUCtZQbP335EeiMhcoXHCIQKFwGR7f/cBArrdSDyFJ9hYjdYEmVP6jHzYCZov7pGowDfax0DX/n1SmUfpr5dKcUA4y8JbqpF8UTYPULiaiRaX7nwU8hcx7o9HCf/HOHRulEgz0DjyBatO5GGZ7eL/bU6roZq51mlNkeaNgT7x7FkELl3/OcO6bbG+1+mYbTUUx1i1p6+V+dw5SvLt+NFPjG+57dfGt20x29EbJmco+PwCYiKWhOMpfIhn53XSknMyvtYxpl64QGAXoLb/hmMg4MeX4xolkjmdn/hC8oiPb5+R8H+Ki+PR25eghFxlAiqBF725nHgkQ+Xe9xhVonTs274jDnK2w+1bqTJkeEBSsm5zr1BcFmK50B8XXmFEyOMf8ng41TtUJHEabk/jm7hqcNTraMR4DjYKbbrK5XUjJZCSluf+79vJzhthPGLxxhUSZhuZmHnF3ziacsfwQX36nKTX15dTTxMzMNLEhyx35OJKsFlUPYATpbxOHuAr0HJSfCjEBlUiWfa6ZmFHuk/7blHbW32AxvgttxIWq1H/0wKGYVgUxhJ7pl+4qSn6D7vZx6AlKw//EjJnAs0BLpnR4Cg8z4N+b6D6yN2BbdaNTj3JuJ+E0ViCxrJCUVOhPxk90cYC0IhtsdGBF1E2Kvwynk3i/lp04b41KlUel9iva8p877WVfUp318t7m7nIlLxeM7Zpcm+iY6lzIxspD/HhtqxCot9nin6lO/YzUcZF/Hpp06C9ZV20hHnw8V+6VAbBJ4EAf1B76BTazwiqbBMGCxd/DlPWlPbJjQXb2Iwrw==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-connection
      namespace: webmap

