# Only needed if microservice contains db migrations
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: k8s-wait-for
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
rules:
  - apiGroups: ['']
    resources: ['services', 'pods', 'jobs']
    verbs: ['get', 'watch', 'list']
  - apiGroups: ['batch']
    resources: ['services', 'pods', 'jobs']
    verbs: ['get', 'watch', 'list']
