# Only needed if microservice contains db migrations
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-wait-for
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
subjects:
  - kind: ServiceAccount
    name: default
    namespace: webmap
roleRef:
  kind: ClusterRole
  name: k8s-wait-for
  apiGroup: rbac.authorization.k8s.io
